export const FETCH_RECIPES_INIT     = 'FETCH_RECIPES_INIT';
export const FETCH_RECIPES_COMPLETE = 'FETCH_RECIPES_COMPLETE';
export const FETCH_RECIPES_FAIL     = 'FETCH_RECIPES_FAIL';
export const NEW_RECIPE             = 'NEW_RECIPE';
export const SEARCH_RECIPE          = 'SEARCH_RECIPE';
export const RESET_SEARCH           = 'RESET_SEARCH';

export const USER_REGISTER_INIT     = 'USER_REGISTER_INIT';
export const USER_REGISTER_COMPLETE = 'USER_REGISTER_COMPLETE';
export const USER_REGISTER_FAIL     = 'USER_REGISTER_FAIL';
export const USER_SIGN_IN_INIT      = 'USER_SIGN_IN_INIT';
export const USER_SIGN_IN_COMPLETE  = 'USER_SIGN_IN_COMPLETE';
export const USER_SIGN_IN_FAIL      = 'USER_SIGN_IN_FAIL';

export const ERROR_NETWORK          = 'ERROR_NETWORK';
